import Image from "next/image";
import { Header } from "@/components/Header";
import { Icon } from "@/components/Icons";
import { InquiryForm } from "@/components/InquiryForm";
import { business, products, whatsappUrl } from "@/lib/site";

const features = [
  ["leaf", "Premium Quality Spices"], ["shield", "100% Natural & Pure"], ["box", "Hygienic Processing"], ["globe", "Domestic & Export Supply"], ["heart", "Customer Satisfaction"],
] as const;
const reasons = ["Premium Quality Spices", "Hygienic Packaging", "Fresh & Authentic Products", "Competitive Prices", "Domestic & Export Supply", "Customer Satisfaction"];
const qualityPoints = ["100% Natural & Pure", "Zero additives", "Hygienic processing", "Maximum freshness", "Careful sourcing", "Professional packaging", "International shipping standards"];

export default function Home() {
  return <><Header business={business} /><main>
    <section className="hero" id="home"><Image className="hero-image" src={business.assets.hero} fill sizes="100vw" priority alt="An assortment of Indian spices in bowls" /><div className="hero-overlay" /><div className="wrap hero-content"><p className="eyebrow light">FROM INDIA TO THE WORLD</p><h1>Premium Indian Spices<br /><em>for Every Kitchen</em></h1><p className="hero-lead">Pure Taste. Premium Quality. Global Trust.</p><p className="hero-subline">From India&apos;s Finest Spices to the World&apos;s Kitchens</p><div className="hero-actions"><a className="button" href="#products">Explore Products <Icon name="arrow" size={17} /></a><a className="button button-ghost" href={whatsappUrl("Hello SAMIRAQ GLOBAL, I would like to know more about your spice range.")} target="_blank" rel="noreferrer">WhatsApp Now</a></div></div><a className="hero-scroll" href="#about">Discover our story <span>↓</span></a></section>
    <section className="feature-bar"><div className="wrap feature-grid">{features.map(([icon, label]) => <div className="feature" key={label}><Icon name={icon} /><span>{label}</span></div>)}</div></section>
    <section className="section about" id="about"><div className="wrap split-about"><div><p className="eyebrow">THE SAMIRAQ STANDARD</p><h2>Authentic spices,<br /><em>thoughtfully supplied.</em></h2><p className="body-copy">SAMIRAQ GLOBAL is an Indian spice company dedicated to delivering premium-quality spices with purity, freshness and authentic Indian taste.</p><p className="body-copy">We carefully source products from trusted suppliers and focus on quality, hygiene, customer satisfaction and reliable service for domestic and international buyers.</p><a className="text-link" href="#quality">Our quality approach <Icon name="arrow" size={17} /></a></div><div className="mission-card"><div><span>Our Mission</span><p>To provide pure, hygienic and premium-quality Indian spices while building a trusted global brand.</p></div><div><span>Our Vision</span><p>To become a globally recognized Indian spice brand known for quality, trust and customer satisfaction.</p></div></div></div></section>
    <section className="section products-section" id="products"><div className="wrap"><div className="section-heading centered"><p className="eyebrow">OUR SELECTION</p><h2>Our Products</h2><p>Authentic Indian Spices for a Better Taste</p></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.slug}><div className="product-image"><Image src={product.image} fill sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 33vw" alt={`${product.name} from SAMIRAQ GLOBAL`} /></div><div className="product-copy"><p>{product.hindiName}</p><h3>{product.name}</h3><span>{product.description}</span><a className="text-link" href="#inquiry">Inquiry / Get Quote <Icon name="arrow" size={16} /></a></div></article>)}</div><div className="center-action"><a className="button button-outline" href="#inquiry">View Products & Request a Quote</a></div></div></section>
    <section className="section quality-section" id="quality"><div className="wrap quality-layout"><div className="quality-visual"><div className="quality-circle"><Icon name="shield" size={44} /><strong>Quality<br />First</strong></div></div><div><p className="eyebrow">OUR QUALITY PROMISE</p><h2>Care in every<br /><em>aromatic detail.</em></h2><p className="body-copy">We focus on ingredients that meet the expectations of professional kitchens, retailers and B2B buyers—without making claims beyond what our products and processes support.</p><div className="quality-list">{qualityPoints.map((point) => <div key={point}><Icon name="check" size={18} />{point}</div>)}</div></div></div></section>
    <section className="section why-section"><div className="wrap"><div className="section-heading"><p className="eyebrow">WHY SAMIRAQ GLOBAL</p><h2>Built for trusted supply.</h2></div><div className="reason-grid">{reasons.map((reason, index) => <div className="reason" key={reason}><span>0{index + 1}</span><h3>{reason}</h3><p>Professional service shaped around your product and quotation requirements.</p></div>)}</div></div></section>
    <section className="export-section" id="export"><Image src={business.assets.hero} fill sizes="100vw" alt="Indian whole spices arranged in bowls" /><div className="export-overlay" /><div className="wrap export-content"><p className="eyebrow light">B2B & INTERNATIONAL INQUIRIES</p><h2>Exporting Quality,<br /><em>Building Global Trust</em></h2><p>Supplying Premium Indian Spices to Domestic & International Markets from {business.location}.</p><a className="button" href="#export-inquiry">Export Inquiry <Icon name="arrow" size={17} /></a></div></section>
    <section className="section export-inquiry" id="export-inquiry"><div className="wrap form-layout"><div><p className="eyebrow">INTERNATIONAL BUYERS</p><h2>Let&apos;s discuss your<br /><em>spice requirement.</em></h2><p className="body-copy">Tell us the product, destination, quantity and packaging requirements. Our quotation workflow is designed for B2B enquiries.</p><div className="contact-mini"><Icon name="pin" /><span>{business.location}</span></div></div><InquiryForm exportMode /></div></section>
    <section className="section certifications" id="certifications"><div className="wrap"><div className="section-heading centered"><p className="eyebrow">BUSINESS INFORMATION</p><h2>Registrations</h2><p>Registration details can be provided upon request and updated here from official documents.</p></div><div className="cert-grid"><Registration title="GST Registered Business" description="Registration number available for authorised business verification." /><Registration title="MSME / Udyam" description="Registration details are maintained as editable business information." /><Registration title="Import Export Code (IEC)" description="IEC details can be added from official documentation." /><Registration title="FSSAI — Coming Soon" description="No licence status or number is displayed until official documentation is supplied." pending /></div></div></section>
    <section className="section contact-section" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">GET IN TOUCH</p><h2>Let&apos;s bring authentic<br /><em>flavour to your business.</em></h2><p className="body-copy">For product enquiries, domestic supply or export quotations, our team is ready to understand your requirements.</p><div className="contact-details"><a href={`mailto:${business.email}`}><Icon name="mail" /><span><small>Email</small>{business.email}</span></a><a href="tel:+919827642435"><Icon name="phone" /><span><small>Ashim Khan</small>{business.phones[0]}</span></a><a href="tel:+917489168059"><Icon name="phone" /><span><small>Shoaib Akhtar</small>{business.phones[1]}</span></a><div><Icon name="pin" /><span><small>Location</small>{business.location}</span></div></div></div><div id="inquiry"><h3>Request a quotation</h3><p>Share your requirements and prepare your enquiry for WhatsApp.</p><InquiryForm /></div></div></section>
  </main><Footer /></>;
}

function Registration({ title, description, pending = false }: { title: string; description: string; pending?: boolean }) { return <article className="cert-card"><Icon name={pending ? "leaf" : "shield"} size={28} /><h3>{title}</h3><p>{description}</p></article>; }

function Footer() {
  const social = Object.entries(business.social) as [keyof typeof business.social, string][];
  return <footer><div className="wrap footer-grid"><div><Image src={business.assets.logo} width={88} height={88} alt="SAMIRAQ GLOBAL logo" /><p>SAMIRAQ GLOBAL supplies authentic Indian spices with a focus on quality, hygiene and reliable service for domestic and international buyers.</p></div><div><h3>Quick Links</h3><a href="#about">About Us</a><a href="#products">Products</a><a href="#export">Export</a><a href="#quality">Quality</a></div><div><h3>Contact</h3><a href={`mailto:${business.email}`}>{business.email}</a><a href="tel:+919827642435">{business.phones[0]}</a><a href="tel:+917489168059">{business.phones[1]}</a><span>{business.location}</span></div><div><h3>Follow Us</h3><p>Social channels will appear here when their official URLs are added.</p><div className="socials">{social.map(([name, url]) => url ? <a href={url} key={name} aria-label={name}><Icon name={name} /></a> : <span aria-label={`${name} link to be added`} key={name}><Icon name={name} /></span>)}</div></div></div><div className="wrap copyright">© 2026 SAMIRAQ GLOBAL. All Rights Reserved.</div></footer>;
}
