import { NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const allowedTypes = new Set(["image/png", "image/jpeg", "image/webp", "image/avif"]);
const maxSize = 8 * 1024 * 1024;
async function verifyAdmin() { const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return null; const { data: profile } = await supabase.from("admin_profiles").select("role").eq("id", user.id).maybeSingle(); return profile?.role === "admin" ? user : null; }

export async function GET() { const user = await verifyAdmin(); if (!user) return NextResponse.json({ error: "Unauthorised" }, { status: 401 }); const admin = createSupabaseAdminClient(); const { data, error } = await admin.from("media_assets").select("*").order("created_at", { ascending: false }); return error ? NextResponse.json({ error: error.message }, { status: 500 }) : NextResponse.json(data); }
export async function POST(request: Request) { const user = await verifyAdmin(); if (!user) return NextResponse.json({ error: "Unauthorised" }, { status: 401 }); const form = await request.formData(); const file = form.get("file"); const altText = String(form.get("altText") || "").slice(0, 300); if (!(file instanceof File) || !allowedTypes.has(file.type) || file.size > maxSize) return NextResponse.json({ error: "Upload a PNG, JPEG, WebP or AVIF image no larger than 8 MB." }, { status: 400 }); const extension = file.name.split(".").pop()?.toLowerCase() || "png"; const path = `${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}.${extension}`; const admin = createSupabaseAdminClient(); const { error: uploadError } = await admin.storage.from("website-media").upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) return NextResponse.json({ error: uploadError.message }, { status: 500 }); const { data: url } = admin.storage.from("website-media").getPublicUrl(path); const { data, error } = await admin.from("media_assets").insert({ storage_path: path, public_url: url.publicUrl, alt_text: altText, mime_type: file.type, file_size: file.size, created_by: user.id }).select().single(); if (error) { await admin.storage.from("website-media").remove([path]); return NextResponse.json({ error: error.message }, { status: 500 }); } return NextResponse.json(data, { status: 201 }); }
