"use client";
import { FormEvent, useState } from "react";
import { products as defaultProducts, quantityOptions as defaultQuantityOptions, whatsappUrl } from "@/lib/site";
type FormValues = Record<"name" | "company" | "email" | "phone" | "country" | "product" | "quantity" | "packaging" | "message", string>;
const initial: FormValues = { name: "", company: "", email: "", phone: "", country: "", product: "", quantity: "", packaging: "", message: "" };
type ProductOption = { name: string };
export function InquiryForm({ exportMode = false, products = defaultProducts, quantityOptions = defaultQuantityOptions, whatsappNumber }: { exportMode?: boolean; products?: readonly ProductOption[]; quantityOptions?: readonly string[]; whatsappNumber?: string }) {
  const [values, setValues] = useState(initial); const [submitted, setSubmitted] = useState(false); const [errors, setErrors] = useState<string[]>([]); const [sending, setSending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.name || !values.email || !values.phone || !values.country || !values.product || !values.quantity) { setErrors(["Please complete your name, email, phone/WhatsApp, country, product, and required quantity."]); return; } setSending(true); setErrors([]); const response = await fetch("/api/enquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enquiryType: exportMode ? "export" : "contact", name: values.name, companyName: values.company, email: values.email, phone: values.phone, country: values.country, productName: values.product, requiredQuantity: values.quantity, packagingRequirement: values.packaging, message: values.message }) }).catch(() => null); setSending(false); if (!response?.ok) { const result = response ? await response.json() : null; setErrors([result?.error || "We could not submit your enquiry. Please use WhatsApp."]); return; } setSubmitted(true); }
  const message = `Hello SAMIRAQ GLOBAL, I am ${values.name || "interested in your products"}${values.company ? ` from ${values.company}` : ""}. I would like a quotation for ${values.product || "spices"}, quantity: ${values.quantity || "to be discussed"}. Country: ${values.country || "not specified"}. ${values.message}`;
  return <form className="inquiry-form" onSubmit={submit} noValidate><div className="form-grid"><Field label="Name" required value={values.name} onChange={(name) => setValues({ ...values, name })} /><Field label="Company Name" value={values.company} onChange={(company) => setValues({ ...values, company })} /><Field label="Email" type="email" required value={values.email} onChange={(email) => setValues({ ...values, email })} /><Field label="Phone / WhatsApp" type="tel" required value={values.phone} onChange={(phone) => setValues({ ...values, phone })} /><Field label={exportMode ? "Destination Country" : "Country"} required value={values.country} onChange={(country) => setValues({ ...values, country })} /><label>Product <span>*</span><select value={values.product} onChange={(e) => setValues({ ...values, product: e.target.value })}><option value="">Select product</option>{products.map((product) => <option key={product.name}>{product.name}</option>)}</select></label><label>Required Quantity <span>*</span><select value={values.quantity} onChange={(e) => setValues({ ...values, quantity: e.target.value })}><option value="">Select quantity</option>{quantityOptions.map((quantity) => <option key={quantity}>{quantity}</option>)}</select></label>{exportMode && <Field label="Packaging / Private-label Requirement" value={values.packaging} onChange={(packaging) => setValues({ ...values, packaging })} />}</div><label>Message<textarea rows={4} value={values.message} onChange={(e) => setValues({ ...values, message: e.target.value })} placeholder="Tell us about your requirement" /></label>{errors.map((error) => <p className="form-error" key={error}>{error}</p>)}{submitted && <div className="form-success"><strong>Your enquiry has been received.</strong><br />Our team will review it. You may also send the prepared details via WhatsApp.</div>}<div className="form-actions"><button className="button" type="submit" disabled={sending}>{sending ? "Sending…" : "Send Enquiry"}</button>{submitted && <a className="button button-outline" href={whatsappUrl(message, whatsappNumber)} target="_blank" rel="noreferrer">Send via WhatsApp</a>}</div></form>;
}
function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label>{label} {required && <span>*</span>}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
